# Generated by Django 3.2.7 on 2021-09-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_id', models.CharField(max_length=10)),
                ('semester', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
