# Generated by Django 3.2.7 on 2021-09-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_enroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='limited_seat',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
