# Generated by Django 3.2.7 on 2021-09-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_subject_limited_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
