# Generated by Django 3.2.7 on 2021-09-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_subject_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_id',
            new_name='subject_code',
        ),
    ]
