# Generated by Django 3.2.7 on 2021-09-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_rename_subject_id_subject_subject_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sName', models.CharField(max_length=100)),
                ('course', models.ManyToManyField(blank=True, related_name='student', to='subjects.Subject')),
            ],
        ),
    ]
