# Generated by Django 3.2.7 on 2021-09-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enroll',
            new_name='IEnroll',
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='studentlist', to='subjects.Subject'),
        ),
    ]
