# Generated by Django 3.2.7 on 2021-09-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_auto_20210918_1328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IEnroll',
        ),
    ]
